apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-app
  annotations:
    'jenkins.io/job-full-name': cft/pipeline
spec:
  type: service
  lifecycle: experimental
  owner: user:tim.jacomb@hmcts.net
