apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-app
  annotations:
    jenkins.io/job-full-name: cft:workflow-multi
    github.com/project-slug: hmcts/azure-platform-terraform
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
spec:
  type: service
  lifecycle: experimental
  owner: 6a5ae2c1-4
