apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ccd-data-store-api
  annotations:
    jenkins.io/job-full-name: cft:workflow-multi
    github.com/project-slug: hmcts/ccd-data-store-api
  tags:
    - java
    - cft
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=ccd_support
      title: ccd_support on Slack
      icon: chat
spec:
  type: service
  lifecycle: experimental
  owner: dcd_ccd
  system: ccd
  providesApis:
    - ccd-data-store-api
  dependsOn:
    - Resource:ccd-data-store-api
