apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rpe-pdf-service
  annotations:
    jenkins.io/job-full-name: cft:workflow-multi
    github.com/project-slug: hmcts/rpe-pdf-service
  links:
    - url: https://github.com/hmcts/rpe-pdf-service
      title: Repo
      icon: user
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  lifecycle: experimental
  owner: dts_platform_operations
  system: pdf-service
