apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ccd-definition-store-api
  annotations:
    jenkins.io/job-full-name: cft:workflow-multi
    github.com/project-slug: hmcts/ccd-definition-store-api
  links:
    - url: https://github.com/hmcts/cnp-plum-recipes-service
      title: Repo
      icon: user
spec:
  type: service
  lifecycle: experimental
  owner: f7f2ea64-4b8c-48a4-b506-b713a3a05000
  system: ccd
  dependsOn:
    - ccd-data-store-api
