apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: draft-store
  description: Allows data to be stored as draft before submission
spec:
  owner: dts_platform_operations
  domain: case-management
